FROM ruby:2.3.5
MAINTAINER Yosuke Torii jinjorweb@gmail.com

RUN useradd --user-group --create-home --shell /bin/false app &&\
    gem install sass

ENV HOME=/home/app

USER app

WORKDIR $HOME

ENTRYPOINT ["sass"]
